
import Pkg 

# List of packages to install
Pkg.add([
    "Measurements",
    "FileIO",
    "HDF5",
    "LinearAlgebra",
    "Images",
    "Statistics",
    "FFTW",
    "Plots",
    "GLMakie",
    "LaTeXStrings",
    "Format",
    "Graphs",
    "MetaGraphsNext",
    "Combinatorics",
    "Optim",
    "GraphMakie",
    "NetworkLayout",
    "Random",
    "GeometryBasics",
    "Colors",
    "Polynomials",
    "Peaks",
    "SphericalHarmonics",
    "StatsBase",
    "Polylabel",
    "LsqFit",
    "CSV",
    "DataFrames",
    "Distributions",
    "XLSX",
    "PaddedViews",
    "Distances",
    "Rotations",
    "ForwardDiff",
    "StaticArrays",
    "Hungarian"
])
